contexts:
  default:
    defaultIde: vscode
    defaultProvider: docker
    options:
      SSH_INJECT_DOCKER_CREDENTIALS:
        userProvided: true
        value: "true"
      SSH_INJECT_GIT_CREDENTIALS:
        userProvided: true
        value: "true"
    providers:
      docker:
        creationTimestamp: "2025-03-15T23:43:27Z"
        initialized: true
        options:
          DOCKER_BUILDER: {}
          DOCKER_HOST: {}
          DOCKER_PATH:
            value: docker
          INACTIVITY_TIMEOUT: {}
        singleMachine: true
defaultContext: default
