name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- uninstall --no-confirm

      - name: Install Flake
        run: nix profile install github:snowfallorg/flake

      - name: Build Darwin
        run: flake build-darwin macos
