name: Compile Markdown CSS

on:
  push:
    paths:
      - 'src/markdown/markdown-body.scss'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Compile SCSS to CSS
      run: npx sass src/markdown/markdown-body.scss dist/markdown-body.css

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add dist/markdown-body.css
        git commit -m 'Compile markdown-body.scss to CSS'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}